### ISSUE TITLE
Invalid properties yield no error message

### ISSUE THREAD

**Issue by ianhbell** [pycalphad/pycalphad#568] opened 2024-09-12 11:50 UTC
My goal is to calculate the molar volume in liquids in pycalphad, but that seems impossible. We can define $\rho=\partial p/\partial g|T$, so I thought I could do something like this:
```python
def get_rho_CALPHAD(*, atom, T_K, P_Pa):
    wks = Workspace('unary50edt.tdb', [atom], ['LIQUID'], {v.T: T_K, v.P: P_Pa, v.N: 1})
    return 1/wks.get(as_property("GM.P"))
```
but it doesn't work, and I get 0, even though it should probably be an exception?

Version 0.11 if that makes any difference.

**Comment by bocklund** [comment] 2024-09-12 17:42
I would expect `wks.get(“GM.P”)` to be correctly implemented, but your database would need to have some pressure dependent Gibbs energies for it to be non-zero. If your database has pressure dependence and is incorrectly giving zero, can you share an example that I can reproduce?

There’s also some partial support for the pressure-independent part of the Lu 2005 molar volume model (https://doi.org/10.1016/j.actamat.2005.01.049) where you would `wks.get(“VM”)`. I think these model parameters are the most prevalent.

**Comment by bocklund** [comment] 2024-09-16 21:05
It's a valid argument that un-physical properties and model values should be able to fail more loudly. However, 
1. due to the dynamic nature of PyCalphad, where arbitrary properties are allowed to be defined on `Model` classes and used throughout the rest of the code, and
2. the convention in the Calphad community typically being that no parameters implies zero

I think it makes sense to close this as a wont-fix for now. It might be worth revisiting this in the future if the community conventions change or if there's an elegant way to determine the validity of a property just-in-time, in a way that respects the dynamic nature of `Model` attributes.

**Closed by bocklund** 2024-09-16 21:05 UTC

**Comment by ianhbell** [comment] 2024-09-16 22:42
Fine by me, was surprising behavior to me that's all
