### ISSUE TITLE
About phase diagrams in multicomponent systems

### ISSUE THREAD

**Issue by by-student-2017** [pycalphad/pycalphad#504] opened 2023-12-14 00:52 UTC
In a multi-element system (A, B, C,...), I would like to fix the molar concentrations of all elements except the two aspects of interest (A and B) and plot the temperature on the vertical axis. The horizontal axis is X(B).

I would also like to draw a longitudinal cross-sectional diagram with temperature as the vertical axis in a ternary system.

It may be possible with Pandat, OpenCALPHAD, etc. How is this possible with Pycalphad?

For example, for A-B-C, a bin plot where the molar concentration of C was fixed across conditions did not work.

I would appreciate it if you could give me some advice.

I would be happy if you could implement it or create an example so that experimental users can easily calculate it.

**Comment by bocklund** [comment] 2024-07-12 00:57
Closing as a duplicate of #5

**Closed by bocklund** 2024-07-12 00:57 UTC
Labels: mapping
