### ISSUE TITLE
Equilibrium not correctly reached for some temperatures

### ISSUE THREAD

**Issue by jaYINGLING** [pycalphad/pycalphad#451] opened 2023-01-04 23:48 UTC
[equilib_temp_fail.zip](https://github.com/pycalphad/pycalphad/files/10348089/equilib_temp_fail.zip)

See the attached database file and python script in which the correct equilibrium is not reached for some temperatures. 
![equilibrium_failure](https://user-images.githubusercontent.com/37126096/210665117-d82ec2ba-ecd6-4f8c-abf7-5fb719854897.png)
Line 97 of eqplot.py was changed to 'return None' to produce this figure.

This failure occurs for this database using pycalphad installations on multiple computers, however, the quantity of failures and temperature values that fail are sometimes different.

**Comment by bocklund** [comment] 2024-07-12 00:47
This is a pseudo binary, so the most correct thing is to use a chemical potential condition (`v.MU`) or an activity condition (not currently supported). Incoming mapping support should improve isopleth support in general, psuedobinaries may improve as well.

**Comment by bocklund** [comment] 2024-07-12 00:52
Closing as a duplicate of #438

**Closed by bocklund** 2024-07-12 00:52 UTC
Labels: mapping, convergence
