### ISSUE TITLE
Unexpected output for calculations on Python 3.11

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#497] opened 2023-11-20 23:41 UTC
When doing equilibrium calculations, there's some printed output that shows up only on Python 3.11 on multiple platforms (confirmed on Ubuntu and macOS in our CI runs).

```
Attribute 'uwtable' should have an Argument
ptr @0
```

Some searching seems to indicate that this is from LLVM, so probably related to symengine or our use of it. It doesn't appear to affect the correctness of any calculations, but is an annoyance if reading through printed output.

**Comment by richardotis** [comment] 2023-11-24 15:33
This is probably related to https://github.com/symengine/symengine/issues/1943, which was fixed in https://github.com/symengine/symengine/pull/1945 and released in symengine 0.10.x. I checked recent CI where this issue appears and we're still pinned to symengine 0.9.2. Now that the symengine 0.11.x series is out, we're probably overdue to resolve the regressions and either bump or relax the version pin.

**Closed** 2023-11-24 18:22 UTC
