### ISSUE TITLE
Plotting phase diagrams with the associate model 

### ISSUE THREAD

**Issue by wahab2604** [pycalphad/pycalphad#278] opened 2020-09-15 15:07 UTC
Hi, 

I have a tdb thats implementated an associates model but I think that pycalphad is incorrectly reading the associates. 
I have attached the phase diagram generated from pycalphad and PANDAT from the tdb in question. Is there something I should change in the tdb or pycalphad setup or is an associates model not supported
![pycalphad2](https://user-images.githubusercontent.com/55495976/93228402-5521dd00-f76d-11ea-99bc-594cafb55237.PNG)
![pycalphad1](https://user-images.githubusercontent.com/55495976/93228411-58b56400-f76d-11ea-8107-aa95bc46308b.PNG)

**Comment by richardotis** [comment] 2020-09-15 15:21
Can you share the TDB file?

**Comment by bocklund** [comment] 2021-04-27 23:32
@wahab2604 are you still having issues with plotting phase diagrams with phases that contain associates?

**Comment by wahab2604** [comment] 2021-04-27 23:44
![CS_final](https://user-images.githubusercontent.com/55495976/116325354-de949580-a7b9-11eb-927a-ec50414357f9.png)
![CS_pandat](https://user-images.githubusercontent.com/55495976/116325509-3e8b3c00-a7ba-11eb-9e2a-4db1865ce99f.PNG)

Thanks for reminding me about this issue, I was going to open a new one. The diagram is plotting fine but there is discrepancy on the liquid immisicibility gap, this might be an issue not related to the associates. I am using the binplot function to plot and espei to  plot the data as per the espei recipes.  Maybe I need to change the calculation conditions ?

**Comment by bocklund** [comment] 2021-04-28 18:48
Great, thanks for the update! 

In the current implementation of `binplot` your ability to resolve small features in composition (and to some extent, your ability to resolve miscibility gaps) is controlled by the composition step size in your conditions. Making that smaller is going to control the trade-off between performance and the ability to resolve narrow features in composition space.

That may explain some of the features missing at ~X(Q)=0.25. I'm guessing that the missing top of the miscibility gap is a global minimization issue or a temperature limit/extrapolation issue.

I ran this code on one of the databases you sent me that you were using in ESPEI:


```python
import matplotlib.pyplot as plt
from pycalphad import Database, binplot, variables as v
from pycalphad import equilibrium
dbf = Database('C-S.tdb')
comps = ['L', 'Q']

# Plot phase diagram
conds = {v.P: 101325, v.T: (1500, 3000, 10), v.X('Q'): (0, 1, 0.01)}
binplot(dbf, comps, phases, conds)
plt.show()

# Phase fraction step calculation
# high point density to try to help find the global min
eq = equilibrium(dbf, comps, phases, {v.N: 1, v.P: 101325, v.T: (2000, 2600, 5), v.X('Q'): 0.85}, calc_opts={'pdens': 100_000})
print(eq)
# Plot phase fractions
plt.scatter(eq.T.broadcast_like(eq.NP), eq.NP)
plt.ylim(0, 1)
plt.xlabel('T')
plt.ylabel('NP(LIQUID)')
plt.show()
```

I got these two figures:

![LQ_10T-0 1X](https://user-images.githubusercontent.com/7681751/116455748-71bbe280-a82f-11eb-8f30-660e58750a7e.png)
![global-min-liquid](https://user-images.githubusercontent.com/7681751/116455721-6963a780-a82f-11eb-9207-5565829d50bc.png)

The phase diagram shows a lot better behavior, but is still missing the miscibility gap.

The phase fraction at X(Q)=0.85 is demonstrating that the liquid miscibility gap is ending abruptly. The sharp transition at close to 2100 K from two phases to one instead of smoothly transitioning does suggest that it's not an issue with mapping, but with computing equilibrium. Ending so close to right on 2100 K, my initial guess would have been a temperature limit issue, but I don't see anything in the TDB I have that would cause this.

@wahab2604 if this is working in Pandat, can you do a point calcluation at like 2105 K and see what the total Gibbs energy is and what the compositions and site fractions of the two liquid composition sets are? From there, we can diagnose whether pycalphad is computing energy incorrectly or whether poor sampling is causing global minimization failures?

Also, it would help if we are using the same database, so whichever one you use to test, can you

1. share it with me so I can reproduce your calculations
2. also confirm that pycalphad computes single phase LIQUID (using a version of my script above) using a high point density at the relevant temperature that you use in your pandat test?

**Comment by bocklund** [comment] 2021-04-28 19:15
It turns out that a point density of 10 million was enough to get a miscibility gat at 2105 K, but it did take almost 20 minutes for a point calculation 😳. 

X, Y, and NP were
```
<xarray.DataArray 'X' (N: 1, P: 1, T: 1, X_Q: 1, vertex: 3, component: 2)>
array([[[[[[0.17871845, 0.82128155],
           [0.06001809, 0.93998191],
           [       nan,        nan]]]]]])
Coordinates:
  * N          (N) float64 1.0
  * P          (P) float64 1.013e+05
  * T          (T) float64 2.105e+03
  * X_Q        (X_Q) float64 0.85
  * vertex     (vertex) int64 0 1 2
  * component  (component) <U1 'L' 'Q'
```

```
<xarray.DataArray 'Y' (N: 1, P: 1, T: 1, X_Q: 1, vertex: 3, internal_dof: 4)>
array([[[[[[1.01716880e-07, 6.48870552e-01, 1.89222250e-02,
            3.32207121e-01],
           [1.03892511e-07, 8.83478422e-01, 1.05435761e-02,
            1.05977898e-01],
           [           nan,            nan,            nan,
                       nan]]]]]])
Coordinates:
  * N        (N) float64 1.0
  * P        (P) float64 1.013e+05
  * T        (T) float64 2.105e+03
  * X_Q      (X_Q) float64 0.85
  * vertex   (vertex) int64 0 1 2
```

```
Dimensions without coordinates: internal_dof <xarray.DataArray 'NP' (N: 1, P: 1, T: 1, X_Q: 1, vertex: 3)>
array([[[[[0.75805931, 0.24194069,        nan]]]]])
Coordinates:
  * N        (N) float64 1.0
  * P        (P) float64 1.013e+05
  * T        (T) float64 2.105e+03
  * X_Q      (X_Q) float64 0.85
  * vertex   (vertex) int64 0 1 2
```


pdens=100k gave single phase and 1M points gave a convergence failure with `equilibrium(..., calc_opts={'pdens': 1_000_000}, verbose=True)`:

```
Components: ACAOLIQ BSIO2LIQ C2SLIQ DCSLIQ L Q
Phases: LIQUID
[done]
('Redundant phase:', CompositionSet(LIQUID, [0.07551272 0.92448728], NP=0.20063070436156652, GM=-1132217.9056660917))
Removing CompositionSet(LIQUID, [0.07551272 0.92448728], NP=nan, GM=-1132217.9056660917)
Trying to improve poor solution
Chemical Potentials [ -948693.58651867 -1147177.01121061]
[9.32218182e-12 9.20027813e-17 4.42858994e-15 9.18213834e-05
 1.32104416e-11 5.48268814e-10 3.36141292e-11 9.32219114e-12]
[1.00000000e+00 1.01325000e+05 2.10500000e+03 1.01601519e-07
 7.05667692e-01 1.70029402e-02 2.77329267e-01 1.00000000e+00]
Status: 0 b'Algorithm terminated successfully at a locally optimal point, satisfying the convergence tolerances (can be specified by options).'
Adding CompositionSet(LIQUID, [0.06320747 0.93679253], NP=0.5, GM=-1134662.652500651) Driving force: 31.27636857237667
Trying to improve poor solution
Calculation Failed:  OrderedDict([('N', array(1.)), ('P', array(101325.)), ('T', array(2105.)), ('X_Q', array(0.85))]) b'Maximum number of iterations exceeded (can be specified by an option).'
Chemical Potentials [ -947796.51743304 -1147335.61024174]
[1.50424122e-04 1.48457068e-09 7.14603913e-08 1.18899622e+03
 2.13163281e-04 8.84706000e-03 5.42417624e-04 1.32241841e+02
 2.13457895e-04 8.83053321e-03 5.40582831e-04 1.51612889e-04
 1.82901683e-02]
[1.00000000e+00 1.01325000e+05 2.10500000e+03 1.16513539e-07
 7.05675578e-01 1.70027145e-02 2.77321591e-01 1.10322673e-06
 7.04701580e-01 1.70345346e-02 2.78262782e-01 9.92157826e-01
 7.84217428e-03]
Status: -1 b'Maximum number of iterations exceeded (can be specified by an option).'
Candidate composition set LIQUID at [0.06320747 0.93679253] is not distinct
```

**Comment by wahab2604** [comment] 2021-04-28 20:02
Hi, thanks for your help. I did a point calculation on the tdb file that you have, and got very similar results to what you have just posted. The 'y' values are slighty different but these are only a few decimal places off. 
![PANDAT_CS](https://user-images.githubusercontent.com/55495976/116464760-43a4c580-a864-11eb-9b20-01f9174587d0.jpg)

Is there a solution for the calculation time or how should I alter binplot to get the equilibrium results you have gotten ? 

I'm assuming this also effects the results of espei ?

**Comment by bocklund** [comment] 2021-04-28 20:52
One way you can work around it is by providing a custom set of points for the LIQUID phase that adds some carefully chosen points that trigger new composition sets to be created. Then you can use a relatively low point density and the added points can compensate for the poor sampling by pycalphad’s Halton sampler. 

The question is how to know which site fractions are near the global minimum so you can give them to pycalphad. You could do some calculations in Pandat and add the site fractions “manually” to pycalphad’s generated points. You would then be able to pass the generated+manually added points to binplot as `binplot(..., eq_kwargs={‘calc_opts’: {‘points’: {‘LIQUID’: concatenated_generated_manual_points}}})` and it should work.

On the ESPEI side, yes this probably would affect the calculations, but it’s difficult to quantify how. From what I have seen in my tests, the energy difference is <30J between the single phase and miscibility gap solutions, so the errors that this will produce in the driving force should be small when you compare the correct global minimum solution and the not-global-minimum solution. It also might bias the optimized parameters in such a way that the miscibility gap forms near points where pycalphad can compute the a miscibility gap.

**Comment by richardotis** [comment] 2021-10-06 15:47
I've confirmed that this issue still exists even with the numerical improvements made in #373

**Comment by bocklund** [comment] 2021-11-06 17:21
@richardotis how was this confirmed? Did you have the database or look at another system. I just checked the script above against `develop` and the results look pretty good using the default point densities:


![issue278-pd-develop](https://user-images.githubusercontent.com/7681751/140598146-30310263-d7b8-4167-9ffc-024acbf6bc7f.png)
![issue278-NP-develop](https://user-images.githubusercontent.com/7681751/140598145-e5100ccd-77f3-44ff-acef-f6d9b6a27ce4.png)

The miscibility gap is much better now, but there is some trouble picking up the `L`-rich side, which should definitely be able to be picked up in theory. It might be that the binplot point density could be raised a little.

**Comment by richardotis** [comment] 2021-11-06 23:26
@bocklund It's possible I checked it using #373 + #376 (yet to be merged)

**Comment by richardotis** [comment] 2024-07-12 16:28
@bocklund Email sent

**Comment by wahab2604** [comment] 2024-07-12 17:35
Hey Brandon, completely forgot about this, I have a published CaO-SiO2 tdb you can use (same parameters as that TDB you are using). 
[1-s2.0-S0008884623002235-mmc1.zip](https://github.com/user-attachments/files/16197524/1-s2.0-S0008884623002235-mmc1.zip)

We made a plotting script using the functionality of pycalphad and it works pretty well (sorry should have posted it here when we made it). It was a rough fix to make it "scan" certain temperatures better, don't know if it will be useful to you. 




```
from pycalphad.plot.utils import phase_legend

def custom_phase_legend(static_phases):
    def phase_legend_func(_):
        return phase_legend(static_phases)
    return phase_legend_func


import pycalphad.plot.binary as pcbinary
def diagram_plot(dbf,comps,filename,data=None,Ts=[1000,3300],scanTs=[],x_label=None,plot_title=None,transparent=False, tielines=False, scatter=False):
    phases = dbf.phases.keys()
    phase_legend_generator = custom_phase_legend(phases) 
    phases = list(phases)
    deltaT = 10
    conds = {
        v.N: 1,
        v.P: 101325,
        v.T: (Ts[0],Ts[1], deltaT),
        v.X(str(comps[0])): (0, 1, 0.02)}
   
    zpf_boundaries = pcbinary.map.map_binary(dbf, comps, phases, conds)
    for T in scanTs:
        zpf_boundaries = pcbinary.map.map_binary(dbf, comps, phases, {v.N:1, v.P:101325, v.T:(T,T+10, 1), v.X(str(comps[0])):(0,1,0.005)}, boundary_sets=zpf_boundaries)
        
    fig = plt.figure(figsize=(10, 9))
    ax = fig.gca()
    if data != None :
        from espei.plot import dataplot
        dataplot(comps, phases, conds, data, ax=ax,tielines=tielines)
    ax.set_ylim(conds[v.T][0], conds[v.T][1])
    
    T_list = []
    pcbinary.plot.plot_boundaries(zpf_boundaries, ax=ax, tielines=tielines, scatter=scatter,legend_generator=phase_legend_generator)

    from collections import defaultdict
    regions = defaultdict(list)
    compsets = zpf_boundaries.all_compsets
    for compset in compsets:
        regions[tuple(compset.phases)].append(compset)
    
    for region in regions:
        top = max(regions[region], key=lambda x: x.temperature)
        newconds = {**conds, v.T:(top.a.temperature, top.a.temperature+deltaT-1, 1)}
        zpf_boundaries = pcbinary.map.map_binary(dbf, comps, phases, newconds)
        pcbinary.plot.plot_boundaries(zpf_boundaries, ax=ax, tielines=tielines, scatter=scatter, legend_generator=phase_legend_generator)

        compsets += zpf_boundaries.all_compsets
        
    regions = defaultdict(list)
    for compset in compsets:
        regions[tuple(compset.phases)].append(compset)
    
### Here we determine where there are regions of interest for us to plot as tie lines (i.e. Eutectics, phase transistions, invariants). 
    
    for region in regions:
        top = max(regions[region], key=lambda x: x.temperature)
        T = top.a.temperature
        if T > Ts[1]-0.5 * deltaT:
            #This region extends above the top of the plot, so don't bother trying to tie it off
            continue
        x_l = top.a.composition
        x_h = top.b.composition
        transition_line = ax.plot([x_l, x_h], [T]*2, 'k-')
        x_text = (x_l + x_h) / 2
        if x_text < 0.1:
            horiz_alignment = 'left'
        elif x_text > 0.9:
            horiz_alignment = 'right'
        else:
            horiz_alignment = 'center'
        T_list.append(int(T))
        T_set = set(T_list)
        if len(T_list) != len(T_set):
            T_list.remove(int(T))
            continue
        else:
            ax.text(x_text, T, str(int(T)), horizontalalignment=horiz_alignment, verticalalignment='bottom')

    

#Find Eutectics?

    liq_bottoms = [region.compsets[0] for region in zpf_boundaries.two_phase_regions if 'LIQUID' in region.phases]

    for i in range(0, len(liq_bottoms)):
        for j in range(i+1, len(liq_bottoms)):
            a = liq_bottoms[i]
            b = liq_bottoms[j]
            if a.a.temperature == b.a.temperature:
                T = a.a.temperature
                if 'LIQUID' in a.a.phase_name:
                    x = a.a.composition
                if 'LIQUID' in a.b.phase_name:
                    x = a.b.composition
                eutectic_point = ax.plot([x], [T], 'x',label="eutectic")
    
    pcbinary.plot.plot_boundaries(zpf_boundaries, ax=ax, tielines=tielines, scatter=scatter, legend_generator=phase_legend_generator)
    if data != None :
        from espei.plot import dataplot
        dataplot(comps, phases, conds, data, ax=ax,tielines=tielines)
    if x_label != None:   
        ax.set_xlabel("X("+x_label+")")
    ax.set_ylabel("Temperature (K)")
    ax.set_title(plot_title, fontsize=20)
    fig.tight_layout()
    fig.savefig(filename,dpi=400,transparent=transparent,bbox_inches="tight")
    fig.clear()
    return fig


```

The output is something like this, 

![CS_supplementary](https://github.com/user-attachments/assets/825c4cda-3f40-4206-b5ea-4173e5271f11)

**Comment by bocklund** [comment] 2024-07-20 00:20
The develop branch after #543 gives this now:

```python
from pycalphad import Database, binplot, variables as v

dbf = Database("Supplementary-CaO_SiO2(R2).tdb")
ax = binplot(dbf, ["L", "Q"], dbf.phases.keys(), {v.P: 101325, v.N: 1, v.T: (50, 3500, 20), v.X("Q"): (0, 1, 0.025)})
ax.figure.savefig("L-Q-pd.png", dpi=150, bbox_inches="tight")
```

I think that's sufficient to close this issue. The labelled invariant temperature is a really cool idea and maybe something we should implement :) 


![L-Q-pd](https://github.com/user-attachments/assets/98bed2c5-d40f-43f8-8da4-76c8ae5362df)

**Closed by bocklund** 2024-07-20 00:20 UTC
Labels: mapping, convergence
